export { buildSystemPrompt, FEW_SHOT_EXAMPLES, LOTTIE_CHEATSHEET } from './system-prompt.ts';
export { validateLottie, isLottieJson, autoFixLottie, LottieSchema } from './schema.ts';
export type { LottieAnimation, LottieLayer } from './schema.ts';
export { generateLottie, generateToFile } from './client.ts';
export { qualityGate, summarizeAnimationPreview, refinePrompt, QUALITY_THRESHOLD, MAX_ITERATIONS } from './quality-gate.ts';
export type { QualityReport, AnimationPreviewSummary } from './quality-gate.ts';
export { generateWithQualityGate } from './quality-gated-generate.ts';
export type { QualityGatedResult, GenerateOptions } from './quality-gated-generate.ts';
export { ARCHETYPES, buildArchetypePrompt, buildVariantPlan } from './archetypes.ts';
export type { LottieArchetype, VariantPlanItem } from './archetypes.ts';
export { ATTRIBUTION_FLOW_MOTION_SPEC, CONTEXT_SEQUENCE_MOTION_SPEC, ECOSYSTEM_ORBIT_MOTION_SPEC, COMPOUNDING_TIMELINE_MOTION_SPEC } from './archetypes.ts';
export { MotionSpecSchema, validateMotionSpec, describeMotionSpec, MOTION_SPEC_VERSION } from './motion-spec.ts';
export type { MotionSpec, MotionRole, MotionTrigger } from './motion-spec.ts';
export { productionQualityGate, evaluateProductionRenderProbe, PRODUCTION_QUALITY_THRESHOLD } from './production-quality.ts';
export type { ProductionAnimationMetadata, ProductionQualityReport, ProductionRenderReport } from './production-quality.ts';
export { buildAttributionFlowAnimation } from './attribution-flow.ts';
export type { AttributionFlowVariant } from './attribution-flow.ts';
export { buildReviewCardData } from './review-card.ts';
export type { AnimationGenerationMeta, ReviewCardData, ReviewCardInput } from './review-card.ts';
export { renderShowcaseHtml } from './showcase.ts';
export type { ShowcaseVariant } from './showcase.ts';
export { RetryOrchestrator } from './retry-orchestrator.ts';
export type { RetryPolicy, FailureType, AttemptRecord, GenerationResult } from './retry-orchestrator.ts';
